# Generated by Django 5.0.6 on 2024-07-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
