# Generated by Django 4.2.5 on 2024-08-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0004_hashtag_user_bio_user_followers_user_website_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commented', to='my_auth.tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='my_auth.tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='my_auth.tweet'),
        ),
    ]
